<template>
<div v-show="activeSettingsTab === 'security'" class="section-card mb-3.5 space-y-4 p-3.5 sm:p-4 md:space-y-5 md:p-6">
                        <h2 class="panel-title mb-4 flex items-center text-lg font-semibold sm:text-xl md:mb-5">
                            <span class="panel-icon mr-2 text-2xl"><i class="ri-shield-user-line"></i></span>登录与单点登录
                        </h2>
                        <!-- OIDC 卡片 -->
                        <div class="rounded-[18px] border border-slate-200/80 bg-slate-50 p-3.5 dark:border-white/10 dark:bg-slate-950 sm:p-4">
                            <div class="mb-4 flex flex-col items-start gap-3 border-b border-slate-200/80 pb-4 dark:border-white/10 sm:flex-row sm:items-center sm:justify-between">
                                <div><p class="text-sm font-semibold text-slate-900 dark:text-white">OIDC 登录</p><p class="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">通过支持 OpenID Connect 的身份提供方登录。</p></div>
                                <label class="relative inline-flex cursor-pointer items-center self-end sm:self-center"><input type="checkbox" v-model="systemSettings.oidc_enable" class="sr-only peer" @change="handleSwitchChange('oidc_enable', systemSettings.oidc_enable)"><div class="switch-track"></div><div class="switch-thumb"></div></label>
                            </div>
                            <div class="space-y-4">
                                <div class="setting-group"><label class="field-label" for="oidc_issuer">Issuer URL</label><input id="oidc_issuer" v-model="systemSettings.oidc_issuer" type="url" class="input-modern" placeholder="https://id.example.com" @blur="handleFieldBlur('oidc_issuer', systemSettings.oidc_issuer)" /><div class="field-hint">OIDC 发行方地址，系统将通过该地址发现授权端点。</div></div>
                                <div class="setting-group"><label class="field-label" for="oidc_client_id">Client ID</label><input id="oidc_client_id" v-model="systemSettings.oidc_client_id" type="text" class="input-modern" placeholder="请输入 OIDC Client ID" @blur="handleFieldBlur('oidc_client_id', systemSettings.oidc_client_id)" /></div>
                                <div class="setting-group"><label class="field-label" for="oidc_client_secret">Client Secret</label><input id="oidc_client_secret" v-model="systemSettings.oidc_client_secret" type="password" class="input-modern" :placeholder="systemSettings.oidc_client_secret_configured ? '已配置，留空表示不修改' : '未配置，请输入 Client Secret'" autocomplete="new-password" @blur="handleFieldBlur('oidc_client_secret', systemSettings.oidc_client_secret)" /><div class="field-hint">{{ systemSettings.oidc_client_secret_configured ? '已配置，留空表示不修改' : '启用 OIDC 登录前必须配置' }}</div></div>
                                <div class="setting-row"><div><p class="setting-row-title">首次登录自动创建用户</p><p class="setting-row-hint">关闭后，尚未绑定本地账户的 OIDC 用户无法登录。</p></div><label class="relative inline-flex cursor-pointer items-center self-end md:self-center"><input type="checkbox" v-model="systemSettings.oidc_auto_provision" class="sr-only peer" @change="handleSwitchChange('oidc_auto_provision', systemSettings.oidc_auto_provision)"><div class="switch-track"></div><div class="switch-thumb"></div></label></div>
                                <div class="setting-group"><label class="field-label" for="oidc_super_admin_username">映射超级管理员用户名</label><input id="oidc_super_admin_username" v-model="systemSettings.oidc_super_admin_username" type="text" maxlength="255" class="input-modern" placeholder="留空表示不映射" @blur="handleFieldBlur('oidc_super_admin_username', systemSettings.oidc_super_admin_username)" /><div class="field-hint">OIDC 校验成功后，最终用户名与此值完全一致时登录本地超级管理员账户（区分大小写）。</div></div>
                                <div class="setting-group"><label class="field-label" for="oidc_redirect_url">回调 URL</label><input id="oidc_redirect_url" v-model="systemSettings.oidc_redirect_url" type="url" class="input-modern" placeholder="https://img.example.com/api/auth/oidc/callback" @blur="handleFieldBlur('oidc_redirect_url', systemSettings.oidc_redirect_url)" /><div class="field-hint">需与 OIDC 身份提供方中登记的回调地址完全一致。</div><div class="field-hint rounded-xl bg-slate-100 px-3 py-2 dark:bg-white/5"><span class="font-medium text-slate-600 dark:text-slate-300">当前有效回调地址：</span><code class="break-all">{{ systemSettings.oidc_redirect_url_effective || '尚未生成' }}</code></div></div>
                                <div class="grid gap-4 lg:grid-cols-2">
                                    <div class="setting-group"><label class="field-label" for="oidc_scopes">Scopes</label><input id="oidc_scopes" v-model="systemSettings.oidc_scopes" type="text" class="input-modern" placeholder="openid profile email" @blur="handleFieldBlur('oidc_scopes', systemSettings.oidc_scopes)" /></div>
                                    <div class="setting-group"><label class="field-label" for="oidc_username_claim">用户名 Claim</label><input id="oidc_username_claim" v-model="systemSettings.oidc_username_claim" type="text" class="input-modern" placeholder="preferred_username" @blur="handleFieldBlur('oidc_username_claim', systemSettings.oidc_username_claim)" /></div>
                                </div>
                                <div class="setting-group"><label class="field-label" for="oidc_display_name">登录按钮名称</label><input id="oidc_display_name" v-model="systemSettings.oidc_display_name" type="text" class="input-modern" placeholder="OIDC 登录" @blur="handleFieldBlur('oidc_display_name', systemSettings.oidc_display_name)" /></div>
                            </div>
                        </div>
                        <!-- CAS 卡片 -->
                        <div class="rounded-[18px] border border-slate-200/80 bg-slate-50 p-3.5 dark:border-white/10 dark:bg-slate-950 sm:p-4">
                            <div class="mb-4 flex flex-col items-start gap-3 border-b border-slate-200/80 pb-4 dark:border-white/10 sm:flex-row sm:items-center sm:justify-between">
                                <div><p class="text-sm font-semibold text-slate-900 dark:text-white">CAS 登录</p><p class="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">CAS 3.0 协议，固定使用 <code>/p3/serviceValidate</code> 校验 XML 响应。</p></div>
                                <label class="relative inline-flex cursor-pointer items-center self-end sm:self-center"><input type="checkbox" v-model="systemSettings.cas_enable" class="sr-only peer" @change="handleSwitchChange('cas_enable', systemSettings.cas_enable)"><div class="switch-track"></div><div class="switch-thumb"></div></label>
                            </div>
                            <div class="space-y-4">
                                <div class="setting-group"><label class="field-label" for="cas_server_url">CAS Server URL</label><input id="cas_server_url" v-model="systemSettings.cas_server_url" type="url" class="input-modern" placeholder="https://cas.example.com/cas" @blur="handleFieldBlur('cas_server_url', systemSettings.cas_server_url)" /><div class="field-hint">填写 CAS 服务根地址，无需附加 <code>/login</code> 或 <code>/p3/serviceValidate</code>。</div></div>
                                <div class="setting-row"><div><p class="setting-row-title">首次登录自动创建用户</p><p class="setting-row-hint">关闭后，尚未绑定本地账户的 CAS 用户无法登录。</p></div><label class="relative inline-flex cursor-pointer items-center self-end md:self-center"><input type="checkbox" v-model="systemSettings.cas_auto_provision" class="sr-only peer" @change="handleSwitchChange('cas_auto_provision', systemSettings.cas_auto_provision)"><div class="switch-track"></div><div class="switch-thumb"></div></label></div>
                                <div class="setting-group"><label class="field-label" for="cas_super_admin_username">映射超级管理员用户名</label><input id="cas_super_admin_username" v-model="systemSettings.cas_super_admin_username" type="text" maxlength="255" class="input-modern" placeholder="留空表示不映射" @blur="handleFieldBlur('cas_super_admin_username', systemSettings.cas_super_admin_username)" /><div class="field-hint">CAS3 XML 的 &lt;cas:user&gt; 与此值完全一致时登录本地超级管理员账户（区分大小写）。</div></div>
                                <div class="setting-group"><label class="field-label" for="cas_service_url">Service URL</label><input id="cas_service_url" v-model="systemSettings.cas_service_url" type="url" class="input-modern" placeholder="https://img.example.com/api/auth/cas/callback" @blur="handleFieldBlur('cas_service_url', systemSettings.cas_service_url)" /><div class="field-hint">需在 CAS 服务端允许列表中登记该地址。</div><div class="field-hint rounded-xl bg-slate-100 px-3 py-2 dark:bg-white/5"><span class="font-medium text-slate-600 dark:text-slate-300">当前有效 Service 地址：</span><code class="break-all">{{ systemSettings.cas_service_url_effective || '尚未生成' }}</code></div></div>
                                <div class="setting-group"><label class="field-label" for="cas_display_name">登录按钮名称</label><input id="cas_display_name" v-model="systemSettings.cas_display_name" type="text" class="input-modern" placeholder="CAS 登录" @blur="handleFieldBlur('cas_display_name', systemSettings.cas_display_name)" /></div>
                            </div>
                        </div>
                    </div>
</template>
<script setup>
import { inject } from 'vue';
import { settingsContext } from '@/utils/settingsAccess.js';
const { systemSettings, activeSettingsTab, activeSettingsTabLabel, presetBuckets, supportsPublicImageDomain, hasPublicImageDomain, publicImageDomainInputDisabled, publicImageDomainHint, handleFieldBlur, handleSelectChange, handleSwitchChange, generatedApiToken, tokenGenerating, generateApiToken, generateRandomGraph } = inject(settingsContext);
</script>
